/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class ApplyForRole extends javax.swing.JFrame {

    /**
     * Creates new form ApplyForRole
     */
    private static String cusername="";
    private static String cuserid="";
    
    public void OnStart(String ui, String un)
    {
        cusername=un;
        cuserid=ui;
        loadDepartments(deptsel);
    }
    public ApplyForRole() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backbtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deptsel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        rolesel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        applybtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        backgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(438, 300));
        setMinimumSize(new java.awt.Dimension(438, 300));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(438, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 30));

        backbtn.setBackground(new java.awt.Color(0, 102, 255));
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("     < BACK");
        backbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbtn.setOpaque(true);
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 450, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Select a department");

        deptsel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deptsel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptselActionPerformed(evt);
            }
        });

        jLabel2.setText("Select your preferred role");

        rolesel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Department Leader", "Department Employee" }));
        rolesel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setText("The HR department will get back to you after a review.");

        applybtn.setBackground(new java.awt.Color(0, 102, 255));
        applybtn.setForeground(new java.awt.Color(255, 255, 255));
        applybtn.setText("           APPLY");
        applybtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        applybtn.setOpaque(true);
        applybtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applybtnMouseClicked(evt);
            }
        });

        jLabel5.setText("You may only apply for one department and position.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(applybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deptsel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rolesel, 0, 180, Short.MAX_VALUE))))
                        .addContainerGap(66, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptsel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(applybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 390, 240));

        jPanel3.setBackground(new java.awt.Color(0,0,0,150));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 410, 270));

        backgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/applyback.jpg"))); // NOI18N
        backgrnd.setMaximumSize(new java.awt.Dimension(438, 300));
        backgrnd.setMinimumSize(new java.awt.Dimension(438, 300));
        getContentPane().add(backgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 530, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        // TODO add your handling code here:
        appmenu ap=new appmenu();
        ap.OnStart(cuserid,cusername);
        ap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void applybtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applybtnMouseClicked
        // TODO add your handling code here:
        try
            {
                Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select count(*) from applications where userid='"+cuserid+"'";
                
                ResultSet rs=stmt.executeQuery(sql);
                int c=0;
                if(rs.next())
                {
                    c=Integer.parseInt(rs.getString(1));
                    //already has an application
                    
                }
                if(c>0)
                {
                    JOptionPane.showMessageDialog(null,"You have already applied, multiple applications are not possible ");
                }
                else
                {
                    
                    String s1=deptsel.getSelectedItem().toString();
                    String s2=rolesel.getSelectedItem().toString();
                    String deptid=""+s1.charAt(0);
                    String ro="";
                    if(s2.equals("Department Leader"))
                    {
                        ro="DL";
                    }
                    else
                    {
                        ro="E";
                    }
                Statement istmt=con.createStatement();
                String isql="insert into applications(userid,deptid,arole,status) values('"+cuserid+"','"+deptid+"','"+ro+"','"+"P"+"')";
                
                stmt.executeUpdate(isql);
                JOptionPane.showMessageDialog(null,"Applied ");
                    
                    
                }
            }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null,"Error "+e);

            }
        
    }//GEN-LAST:event_applybtnMouseClicked

    private void deptselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptselActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptselActionPerformed
    private void loadDepartments(JComboBox cbox)
    {
        String[] s=null;
        int i=0;
        int ct=0;
        try
            {
                Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select * from department";
                String c="select count(*) from department";
                ResultSet rsp=stmt.executeQuery(c);
                
                if(rsp.next())
                {
                    ct=Integer.parseInt(rsp.getString(1));
                    s=new String[ct];
                    ResultSet rs=stmt.executeQuery(sql);
                while(rs.next())
                {
                    String id=rs.getString(1);
                    String name=rs.getString(2);
                    String ns=id+". "+name;
                    s[i]=ns;
                    i++;
                }
                cbox.setModel(new DefaultComboBoxModel<>(s));
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error "+e);
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplyForRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplyForRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplyForRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplyForRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplyForRole().setVisible(true);
            }
        });
        
        //call draw here
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applybtn;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel backgrnd;
    private javax.swing.JComboBox<String> deptsel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> rolesel;
    // End of variables declaration//GEN-END:variables
}
