/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

/**
 *
 * @author theam
 */
public class appmenu extends javax.swing.JFrame {

    /**
     * Creates new form appmenu
     */
    private static String cusername="";
    private static String cuserid="";
    
    public void OnStart(String ui, String un)
    {
        cusername=un;
        cuserid=ui;
    }
    public appmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoutb = new javax.swing.JLabel();
        applyj = new javax.swing.JLabel();
        chck = new javax.swing.JLabel();
        upd = new javax.swing.JLabel();
        backapp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(500, 300));
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        logoutb.setBackground(new java.awt.Color(0, 102, 255));
        logoutb.setForeground(new java.awt.Color(255, 255, 255));
        logoutb.setText("     LOGOUT");
        logoutb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutb.setOpaque(true);
        logoutb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 427, Short.MAX_VALUE)
                .addComponent(logoutb, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        applyj.setBackground(new java.awt.Color(0, 102, 255));
        applyj.setForeground(new java.awt.Color(255, 255, 255));
        applyj.setText("        APPLY FOR A ROLE");
        applyj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        applyj.setOpaque(true);
        applyj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                applyjMouseClicked(evt);
            }
        });
        getContentPane().add(applyj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 40));

        chck.setBackground(new java.awt.Color(0, 102, 255));
        chck.setForeground(new java.awt.Color(255, 255, 255));
        chck.setText("           UPDATE DETAILS");
        chck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chck.setOpaque(true);
        chck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chckMouseClicked(evt);
            }
        });
        getContentPane().add(chck, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 190, 40));

        upd.setBackground(new java.awt.Color(0, 102, 255));
        upd.setForeground(new java.awt.Color(255, 255, 255));
        upd.setText("   CHECK APPLICATION STATUS");
        upd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upd.setOpaque(true);
        upd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updMouseClicked(evt);
            }
        });
        getContentPane().add(upd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 190, 40));

        backapp.setBackground(new java.awt.Color(204, 204, 255));
        backapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/applyback.jpg"))); // NOI18N
        backapp.setOpaque(true);
        getContentPane().add(backapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbMouseClicked
        // TODO add your handling code here:
        Login l=new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutbMouseClicked

    private void applyjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_applyjMouseClicked
        // TODO add your handling code here:
        ApplyForRole apr=new ApplyForRole();
        apr.OnStart(cuserid, cusername);
        apr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_applyjMouseClicked

    private void updMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updMouseClicked
        // TODO add your handling code here:
        checkAppStatus cas=new checkAppStatus();
        cas.OnStart(cuserid, cusername);
        cas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updMouseClicked

    private void chckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chckMouseClicked
        // TODO add your handling code here:
        updateApDetails upd=new updateApDetails();
        upd.OnStart(cuserid,cusername);
        upd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_chckMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel applyj;
    private javax.swing.JLabel backapp;
    private javax.swing.JLabel chck;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutb;
    private javax.swing.JLabel upd;
    // End of variables declaration//GEN-END:variables
}
