/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class empupdate extends javax.swing.JFrame {

    /**
     * Creates new form empupdate
     */
    private static String cusername="";
    private static String cuserid="";
    
    boolean canEdit=false;
    
    public void OnStart(String ui, String un)
    {
        cusername=un;
        cuserid=ui;
        LoadData();
        nametf.setEditable(canEdit);
        pwdtf.setEditable(canEdit);
        emailtf.setEditable(canEdit);
        hqcb.setEnabled(canEdit);
        saveb.setEnabled(canEdit);
    }
    
    private void LoadData()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select * from user where userid='"+cuserid+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    nametf.setText(rs.getString(2));
                    emailtf.setText(rs.getString(7));
                    String Q=rs.getString(8);
                    if(Q.equals("School"))
                    {
                        hqcb.setSelectedIndex(0);
                    }
                    else if(Q.equals("PUC"))
                    {
                        hqcb.setSelectedIndex(1);
                    }
                    else if(Q.equals("BE") || Q.equals("B"))
                    {
                        hqcb.setSelectedIndex(2);
                    }
                    else if(Q.equals("M") || Q.equals("MS"))
                    {
                        hqcb.setSelectedIndex(3);
                    }
                    else if(Q.equals("PHD"))
                    {
                        hqcb.setSelectedIndex(4);
                    }
                    else
                    {
                        hqcb.setSelectedIndex(5);
                    }
                }
        }
        catch(Exception e)
        {
            
        }
    }
    public empupdate() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwdtf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hqcb = new javax.swing.JComboBox<>();
        saveb = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setMaximumSize(new java.awt.Dimension(500, 300));
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        backb.setBackground(new java.awt.Color(0, 102, 255));
        backb.setForeground(new java.awt.Color(255, 255, 255));
        backb.setText("     < BACK");
        backb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backb.setOpaque(true);
        backb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 420, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Edit your details");

        jRadioButton1.setText(" EDIT");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("New Password");

        jLabel4.setText("email");

        jLabel5.setText("Highest qualification");

        hqcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School", "PUC", "B", "M", "PHD" }));

        saveb.setBackground(new java.awt.Color(0, 102, 255));
        saveb.setForeground(new java.awt.Color(255, 255, 255));
        saveb.setText("                         UPDATE");
        saveb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveb.setOpaque(true);
        saveb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveb, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nametf)
                            .addComponent(pwdtf)
                            .addComponent(emailtf)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(hqcb, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwdtf)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(hqcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 400, 240));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/empback.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
        canEdit=!canEdit;
        nametf.setEditable(canEdit);
        pwdtf.setEditable(canEdit);
        emailtf.setEditable(canEdit);
        hqcb.setEnabled(canEdit);
        saveb.setEnabled(canEdit);
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void savebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebMouseClicked
        // TODO add your handling code here:
        String newName=nametf.getText().toString();
        String newPassword=pwdtf.getText().toString();
        String newEmail=emailtf.getText().toString();
        String newQ=hqcb.getSelectedItem().toString();
        
        if(!isNotEMP(newPassword))
        {
            newPassword=getOldPassword();
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="update user set username='"+newName+"',password='"+newPassword+"',email='"+newEmail+"',qualifications='"+newQ+"' where userid='"+cuserid+"'";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Updated details ");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
    }//GEN-LAST:event_savebMouseClicked

    private void backbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbMouseClicked
        // TODO add your handling code here:
        empmenu em=new empmenu();
        em.OnStart(cuserid, cusername);
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbMouseClicked
    private boolean isNotEMP(String str){
        
        if(str==null||str.equals("")){
            return false;
        }else{
            return true;
        }
    }
     private String getOldPassword()
    {
        String op="";
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select password from user where userid='"+cuserid+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    op=rs.getString(1);
                }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
        return op;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new empupdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backb;
    private javax.swing.JLabel background;
    private javax.swing.JTextField emailtf;
    private javax.swing.JComboBox<String> hqcb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField nametf;
    private javax.swing.JPasswordField pwdtf;
    private javax.swing.JLabel saveb;
    // End of variables declaration//GEN-END:variables
}
