/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class hrca extends javax.swing.JFrame {

    /**
     * Creates new form hrca
     */
    private static String cusername="";
    private static String cuserid="";

    public void OnStart(String ui, String un)
    {
        cusername=un;
        cuserid=ui;
        LoadApps();
    }
    public hrca() {
        initComponents();
    }
    void LoadApps()
    {
        String[] s=null;
        int i=0;
        int ct=0;
        try
            {
                Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select userid from applications where status='"+"P"+"'";
                String c="select count(*) from applications where status='"+"P"+"'";
                ResultSet rsp=stmt.executeQuery(c);
                
                if(rsp.next())
                {
                    ct=Integer.parseInt(rsp.getString(1));
                    s=new String[ct];
                    ResultSet rs=stmt.executeQuery(sql);
                while(rs.next())
                {
                    String id=rs.getString(1);
                    //String name=rs.getString(2);
                    String ns=id;
                    s[i]=ns;
                    i++;
                }
                appbox.setModel(new DefaultComboBoxModel<>(s));
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error "+e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        appbox = new javax.swing.JComboBox<>();
        viewb = new javax.swing.JLabel();
        namel = new javax.swing.JLabel();
        roll = new javax.swing.JLabel();
        deptl = new javax.swing.JLabel();
        quall = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        backb.setBackground(new java.awt.Color(0, 102, 255));
        backb.setForeground(new java.awt.Color(255, 255, 255));
        backb.setText("    < BACK");
        backb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backb.setOpaque(true);
        backb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 410, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setText("Recieved applications");

        appbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appboxActionPerformed(evt);
            }
        });

        viewb.setBackground(new java.awt.Color(0, 102, 204));
        viewb.setForeground(new java.awt.Color(255, 255, 255));
        viewb.setText("       VIEW");
        viewb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewb.setOpaque(true);
        viewb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbMouseClicked(evt);
            }
        });

        namel.setText("Name");

        roll.setText("Role");

        deptl.setText("Departments");

        quall.setText("Qualifications");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deptl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roll, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appbox, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewb, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deptl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quall, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 440, 140));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/hrback2.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 490, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbMouseClicked
        // TODO add your handling code here:
        hrmenu hr=new hrmenu();
        hr.OnStart(cuserid, cusername);
        hr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbMouseClicked
    
    private void viewbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbMouseClicked
        // TODO add your handling code here:
        String aid=(String) appbox.getSelectedItem();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select u.username,a.arole,a.deptid,u.qualifications from user u,applications a where a.userid='"+aid+"' and u.userid=a.userid";
                
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    namel.setText("Name "+rs.getString(1));
                    String ro=rs.getString(2);
                    String fr="";
                    if(ro.equals("E"))
                    {
                        fr="Employee";
                    }
                    else if(ro.equals("DL"))
                    {
                        fr="Department leader";
                    }
                    roll.setText("Role: "+fr);
                        
                    String deptid=rs.getString(3);
                    deptl.setText("Department id: "+deptid);
                    String qual=rs.getString(4);
                    quall.setText("Qualifications : "+qual);
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error(1) "+e);
        }
    }//GEN-LAST:event_viewbMouseClicked

    private void appboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hrca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hrca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hrca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hrca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hrca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> appbox;
    private javax.swing.JLabel backb;
    private javax.swing.JLabel background;
    private javax.swing.JLabel deptl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel namel;
    private javax.swing.JLabel quall;
    private javax.swing.JLabel roll;
    private javax.swing.JLabel viewb;
    // End of variables declaration//GEN-END:variables
}
