/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

/**
 *
 * @author theam
 */
public class hrmenu extends javax.swing.JFrame {

    /**
     * Creates new form hrmenu
     */
    private static String cusername="";
    private static String cuserid="";

    public void OnStart(String ui, String un)
    {
        cusername=un;
        cuserid=ui;
    }
    public hrmenu() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caps = new javax.swing.JLabel();
        cdps = new javax.swing.JLabel();
        cemp = new javax.swing.JLabel();
        ti = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JLabel();
        backimg2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caps.setBackground(new java.awt.Color(0, 102, 255));
        caps.setForeground(new java.awt.Color(255, 255, 255));
        caps.setText("     CHECK DEPARTMENTS");
        caps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        caps.setOpaque(true);
        caps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capsMouseClicked(evt);
            }
        });
        getContentPane().add(caps, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 30));

        cdps.setBackground(new java.awt.Color(0, 102, 255));
        cdps.setForeground(new java.awt.Color(255, 255, 255));
        cdps.setText("       UPDATE POLICIES");
        cdps.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cdps.setOpaque(true);
        cdps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cdpsMouseClicked(evt);
            }
        });
        getContentPane().add(cdps, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, 30));

        cemp.setBackground(new java.awt.Color(0, 102, 255));
        cemp.setForeground(new java.awt.Color(255, 255, 255));
        cemp.setText("      CHECK EMPLOYEES");
        cemp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cemp.setOpaque(true);
        cemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cempMouseClicked(evt);
            }
        });
        getContentPane().add(cemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 30));

        ti.setBackground(new java.awt.Color(0, 102, 255));
        ti.setForeground(new java.awt.Color(255, 255, 255));
        ti.setText("     CHECK APPLICATIONS");
        ti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ti.setOpaque(true);
        ti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiMouseClicked(evt);
            }
        });
        getContentPane().add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        logoutbtn.setBackground(new java.awt.Color(0, 102, 255));
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setText("    LOGOUT");
        logoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutbtn.setOpaque(true);
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 335, Short.MAX_VALUE)
                .addComponent(logoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        backimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/hrback2.jpg"))); // NOI18N
        backimg2.setPreferredSize(new java.awt.Dimension(500, 170));
        getContentPane().add(backimg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        // TODO add your handling code here:
        Login lg=new Login();
        lg.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void cempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cempMouseClicked
        // TODO add your handling code here:
        hrce ce= new hrce();
        ce.OnStart(cuserid, cusername);
        ce.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cempMouseClicked

    private void capsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capsMouseClicked
        // TODO add your handling code here:
        hrcd hd=new hrcd();
        hd.OnStart(cuserid, cusername);
        hd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_capsMouseClicked

    private void tiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiMouseClicked
        // TODO add your handling code here:
        hrca hr=new hrca();
        hr.OnStart(cuserid, cusername);
        hr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tiMouseClicked

    private void cdpsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cdpsMouseClicked
        // TODO add your handling code here:
        hrup hr=new hrup();
        hr.OnStart(cuserid, cusername);
        hr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cdpsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hrmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hrmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hrmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hrmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hrmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backimg2;
    private javax.swing.JLabel caps;
    private javax.swing.JLabel cdps;
    private javax.swing.JLabel cemp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutbtn;
    private javax.swing.JLabel ti;
    // End of variables declaration//GEN-END:variables
}
