/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class hrup extends javax.swing.JFrame {

    /**
     * Creates new form hrup
     */
    private static String cusername="";
    private static String cuserid="";
    
    boolean canEdit=false;
    public void OnStart(String ui, String un)
    {
        cusername=un;
        cuserid=ui;
        LoadDeps();
        minpostf.setEditable(canEdit);
        mwhtf.setEditable(canEdit);
        updatebtn.setEnabled(canEdit);
    }
    public hrup() {
        initComponents();
    }
    void LoadDeps()
    {
        String[] s=null;
        int i=0;
        int ct=0;
        try
            {
                Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select * from department";
                String c="select count(*) from department";
                ResultSet rsp=stmt.executeQuery(c);
                
                if(rsp.next())
                {
                    ct=Integer.parseInt(rsp.getString(1));
                    s=new String[ct];
                    ResultSet rs=stmt.executeQuery(sql);
                while(rs.next())
                {
                    String id=rs.getString(1);
                    
                    String ns=id;
                    s[i]=ns;
                    i++;
                }
                deptbox.setModel(new DefaultComboBoxModel<>(s));
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"Error "+e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editrb = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        deptbox = new javax.swing.JComboBox<>();
        dn = new javax.swing.JLabel();
        dn1 = new javax.swing.JLabel();
        mwhtf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        minpostf = new javax.swing.JTextField();
        updatebtn = new javax.swing.JLabel();
        loadb = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        backb.setBackground(new java.awt.Color(0, 102, 255));
        backb.setForeground(new java.awt.Color(255, 255, 255));
        backb.setText("      < BACK");
        backb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backb.setOpaque(true);
        backb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 420, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backb, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Edit basic policies");

        editrb.setText(" EDIT");
        editrb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editrbMouseClicked(evt);
            }
        });

        jLabel2.setText("Select department");

        dn.setText("Minimum work hours");

        dn1.setText("Dept name");

        jLabel3.setText("Minimum positions");

        updatebtn.setBackground(new java.awt.Color(0, 102, 255));
        updatebtn.setForeground(new java.awt.Color(255, 255, 255));
        updatebtn.setText("           UPDATE");
        updatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updatebtn.setOpaque(true);
        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
        });

        loadb.setBackground(new java.awt.Color(0, 102, 255));
        loadb.setForeground(new java.awt.Color(255, 255, 255));
        loadb.setText("          LOAD");
        loadb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadb.setOpaque(true);
        loadb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mwhtf)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editrb, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(deptbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(loadb, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addComponent(minpostf))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dn1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editrb))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deptbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loadb)))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dn)
                    .addComponent(mwhtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(minpostf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(dn1)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 380, 250));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/hrback2.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbMouseClicked
        // TODO add your handling code here:
        hrmenu hr=new hrmenu();
        hr.OnStart(cuserid, cusername);
        hr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbMouseClicked

    private void loadbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadbMouseClicked
        // TODO add your handling code here:
         //JOptionPane.showMessageDialog(null,"Clicked ");
        minpostf.setText("");
        mwhtf.setText("");
        String cdid=deptbox.getSelectedItem().toString();
        dn1.setText("Department Name " +getDeptname());
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select p.*,d.deptname from policies p,department d where p.deptid='"+cdid+"' and p.deptid=d.deptid";
                ResultSet rs=stmt.executeQuery(sql);
                //JOptionPane.showMessageDialog(null,"Set ");
                if(rs.next())
                {
                    
                    minpostf.setText(rs.getString(3));
                    mwhtf.setText(rs.getString(2));
                    //JOptionPane.showMessageDialog(null,"Set ");
                }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
    }//GEN-LAST:event_loadbMouseClicked
    private String getDeptname()
    {
        String res="";
        String cdid=deptbox.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select deptname from department where deptid='"+cdid+"'";
                ResultSet rs=stmt.executeQuery(sql);
                //JOptionPane.showMessageDialog(null,"Set ");
                if(rs.next())
                {
                    res=rs.getString(1);
                }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
        return res;
    }
    private void editrbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editrbMouseClicked
        // TODO add your handling code here:
        canEdit=!canEdit;
        minpostf.setEditable(canEdit);
        mwhtf.setEditable(canEdit);
        updatebtn.setEnabled(canEdit);
    }//GEN-LAST:event_editrbMouseClicked
    private boolean isNotEMP(String str){
        
        if(str==null||str.equals("")){
            return false;
        }else{
            return true;
        }
    }
    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        // TODO add your handling code here:
        String cdid=deptbox.getSelectedItem().toString();
        int mwh=0,minp=0;
        
        if(isNotEMP(mwhtf.getText().toString()) && isNotEMP(minpostf.getText().toString()))
            {
                    mwh=Integer.parseInt(mwhtf.getText().toString());
                    minp=Integer.parseInt(minpostf.getText().toString());
       
         try
            {
                Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select count(*) from policies where deptid='"+cdid+"'";
                
                ResultSet rs=stmt.executeQuery(sql);
                int c=0;
                if(rs.next())
                {
                    c=Integer.parseInt(rs.getString(1));
                    //already has an application
                    
                }
                if(c==0)
                {
                    JOptionPane.showMessageDialog(null,"No previous policy found, will apply current entry as policy");
                    Statement istmt=con.createStatement();
                    String isql="insert into policies(deptid,minimumwork,positions) values('"+cdid+"','"+mwh+"','"+minp+"')";
                
                    stmt.executeUpdate(isql);
                    JOptionPane.showMessageDialog(null,"Added ");
                }
                else
                {
                    
                Statement stmt1=con.createStatement();
                String sql1="update policies set minimumwork='"+mwh+"',positions='"+minp+"' where deptid='"+cdid+"'";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Updated policies ");
                    
                    
                }
            }
            catch(Exception e)
            {
              JOptionPane.showMessageDialog(null,"Error "+e);

            }
            }
        else
        {
           JOptionPane.showMessageDialog(null,"Don't leave the fields empty "); 
        }
        
        
        
    }//GEN-LAST:event_updatebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hrup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hrup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hrup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hrup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hrup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backb;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> deptbox;
    private javax.swing.JLabel dn;
    private javax.swing.JLabel dn1;
    private javax.swing.JRadioButton editrb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loadb;
    private javax.swing.JTextField minpostf;
    private javax.swing.JTextField mwhtf;
    private javax.swing.JLabel updatebtn;
    // End of variables declaration//GEN-END:variables
}
