/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        unametf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        upwdtf = new javax.swing.JPasswordField();
        applicationpan = new javax.swing.JPanel();
        appbtn = new javax.swing.JLabel();
        logbtn = new javax.swing.JLabel();
        topbar = new javax.swing.JPanel();
        closebutton = new javax.swing.JLabel();
        bckimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/icons8-employee-48.png"))); // NOI18N

        unametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unametfActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Username");

        jLabel3.setText("Enter Password");

        upwdtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upwdtfActionPerformed(evt);
            }
        });

        appbtn.setBackground(new java.awt.Color(0, 0, 153));
        appbtn.setForeground(new java.awt.Color(255, 255, 255));
        appbtn.setText("                      APPLY FOR ROLE");
        appbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appbtn.setOpaque(true);
        appbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                appbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout applicationpanLayout = new javax.swing.GroupLayout(applicationpan);
        applicationpan.setLayout(applicationpanLayout);
        applicationpanLayout.setHorizontalGroup(
            applicationpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
            .addGroup(applicationpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(appbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );
        applicationpanLayout.setVerticalGroup(
            applicationpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(applicationpanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(appbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        logbtn.setBackground(new java.awt.Color(0, 0, 153));
        logbtn.setForeground(new java.awt.Color(255, 255, 255));
        logbtn.setText("         LOGIN");
        logbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logbtn.setOpaque(true);
        logbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logbtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(applicationpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(upwdtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(logbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(unametf, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(115, 115, 115))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unametf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upwdtf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(applicationpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0,0,0,150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 330, 320));

        topbar.setBackground(new java.awt.Color(0, 102, 255));

        closebutton.setBackground(new java.awt.Color(0, 102, 255));
        closebutton.setForeground(new java.awt.Color(255, 255, 255));
        closebutton.setText("         X");
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.setOpaque(true);
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closebuttonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout topbarLayout = new javax.swing.GroupLayout(topbar);
        topbar.setLayout(topbarLayout);
        topbarLayout.setHorizontalGroup(
            topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topbarLayout.createSequentialGroup()
                .addGap(0, 440, Short.MAX_VALUE)
                .addComponent(closebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topbarLayout.setVerticalGroup(
            topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closebutton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(topbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        bckimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/backlogin.jpeg"))); // NOI18N
        getContentPane().add(bckimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closebuttonMouseClicked

    private void closebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseEntered
        // TODO add your handling code here:
        //change color to red
        closebutton.setBackground(new java.awt.Color(255,10,10));
       closebutton.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_closebuttonMouseEntered

    private void closebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseExited
        // TODO add your handling code here:
        //back to original
        closebutton.setBackground(new java.awt.Color(0,102,255));
       closebutton.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_closebuttonMouseExited

    private void unametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unametfActionPerformed

    private void upwdtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upwdtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upwdtfActionPerformed

    private void logbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbtnMouseEntered
        // TODO add your handling code here:
        logbtn.setBackground(new java.awt.Color(51,153,255));
        logbtn.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_logbtnMouseEntered

    private void logbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbtnMouseExited
        // TODO add your handling code here:
        logbtn.setBackground(new java.awt.Color(0,0,153));
        logbtn.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_logbtnMouseExited

    private void appbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appbtnMouseEntered
        // TODO add your handling code here:
        appbtn.setBackground(new java.awt.Color(51,153,255));
        appbtn.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_appbtnMouseEntered

    private void appbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appbtnMouseExited
        // TODO add your handling code here:
         appbtn.setBackground(new java.awt.Color(0,0,153));
         appbtn.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_appbtnMouseExited
    
    private boolean isNotEMP(String str){
        
        if(str==null||str.equals("")){
            return false;
        }else{
            return true;
        }
    }
    
    private void logbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logbtnMouseClicked
        // TODO add your handling code here:
        //ATTEMPT LOGIN
        String uname=unametf.getText().toString();
        String upwd=upwdtf.getText().toString();
        if(isNotEMP(uname) && isNotEMP(upwd))
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select * from user where username='"+uname+"'";
                
               ResultSet rs=stmt.executeQuery(sql);
               if(rs.next()){
                   String uid=rs.getString(1);
                   String pwd1=rs.getString(3);
                   String role=rs.getString(4);
                   
                   if(pwd1.equals(upwd))
                   {
                       //valid login
                       //JOptionPane.showMessageDialog(null,"Valid Login ");
                       if(role.equals("DL") || role.equals("E"))
                       {
                           empmenu em=new empmenu();
                           em.OnStart(uid,uname);
                           em.setVisible(true);
                           this.dispose();
                           
                       }
                       else if(role.equals("HR"))
                       {
                           hrmenu hr=new hrmenu();
                           hr.OnStart(uid, uname);
                           hr.setVisible(true);
                           this.dispose();
                           
                       }
                       else
                       {
                           appmenu ap=new appmenu();
                           ap.OnStart(uid, uname);
                           ap.setVisible(true);
                           this.dispose();
                       }
                       
                   }
                   else
                   {
                       JOptionPane.showMessageDialog(null,"Invalid Password, try again ");
                   }
               }
               else
               {
                   JOptionPane.showMessageDialog(null,"No such username found ");
               }
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(null,"Please check your network ");
            }
        }
        else
        {
            //print empty fields
            JOptionPane.showMessageDialog(null,"Fields are empty, please fill them with vaild credentials ");
        }
        
        
        
        
    }//GEN-LAST:event_logbtnMouseClicked

    private void appbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appbtnMouseClicked
        // TODO add your handling code here:
        signup su=new signup();
        su.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appbtn;
    private javax.swing.JPanel applicationpan;
    private javax.swing.JLabel bckimg;
    private javax.swing.JLabel closebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logbtn;
    private javax.swing.JPanel topbar;
    private javax.swing.JTextField unametf;
    private javax.swing.JPasswordField upwdtf;
    // End of variables declaration//GEN-END:variables
}
