/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class SimWork extends javax.swing.JFrame {

    /**
     * Creates new form SimWork
     */
    private static String cusername="";
    private static String cuserid="";
    
    public void OnStart(String ui, String un)
    {
        cusername=un;
        cuserid=ui;
    }
    
    public SimWork() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        wmsg = new javax.swing.JLabel();
        hsld = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        hrs = new javax.swing.JLabel();
        simb = new javax.swing.JLabel();
        backgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        backb.setBackground(new java.awt.Color(0, 102, 255));
        backb.setForeground(new java.awt.Color(255, 255, 255));
        backb.setText("     < BACK");
        backb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backb.setOpaque(true);
        backb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 420, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        wmsg.setText("Welcome");

        hsld.setBackground(new java.awt.Color(204, 204, 204));
        hsld.setPaintLabels(true);
        hsld.setPaintTicks(true);
        hsld.setSnapToTicks(true);
        hsld.setValue(2);
        hsld.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                hsldMouseDragged(evt);
            }
        });

        jLabel2.setText("Select the number of work hours to simulate");

        hrs.setText("Hours: ");

        simb.setBackground(new java.awt.Color(0, 102, 255));
        simb.setForeground(new java.awt.Color(255, 255, 255));
        simb.setText("       SIMULATE");
        simb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simb.setOpaque(true);
        simb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wmsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hsld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(hrs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(simb, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wmsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hsld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrs)
                .addGap(18, 18, 18)
                .addComponent(simb, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 290, 200));

        backgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/empback.jpg"))); // NOI18N
        getContentPane().add(backgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbMouseClicked
        // TODO add your handling code here:
        empmenu em =new empmenu();
        em.OnStart(cuserid, cusername);
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbMouseClicked

    private void hsldMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hsldMouseDragged
        // TODO add your handling code here:
        hrs.setText("Hours: "+hsld.getValue());
    }//GEN-LAST:event_hsldMouseDragged

    private void simbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simbMouseClicked
        // TODO add your handling code here:
        int inc=hsld.getValue();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select * from worktbl where userid='"+cuserid+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    int finh=Integer.parseInt(rs.getString(2));
                    finh+=inc;
                    Statement stmti=con.createStatement();
                    String sqli="update worktbl set totalwork='"+finh+"' where userid='"+cuserid+"'";
                    stmti.executeUpdate(sqli);
                    JOptionPane.showMessageDialog(null,"Updated ");
                }
                else
                {
                    
                Statement stmti=con.createStatement();
                String sqli="insert into worktbl(userid,totalwork) values('"+cuserid+"','"+inc+"')";
                stmti.executeUpdate(sqli);
                JOptionPane.showMessageDialog(null,"Added ");
                }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
    }//GEN-LAST:event_simbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimWork.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimWork().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backb;
    private javax.swing.JLabel backgrnd;
    private javax.swing.JLabel hrs;
    private javax.swing.JSlider hsld;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel simb;
    private javax.swing.JLabel wmsg;
    // End of variables declaration//GEN-END:variables
}
