/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrmanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author theam
 */
public class updateApDetails extends javax.swing.JFrame {

    /**
     * Creates new form updateApDetails
     */
    private static String cusername="";
    private static String cuserid="";
    
    boolean canEdit=false;
    
    public void OnStart(String ui, String un)
    {
        cusername=un;
        cuserid=ui;
        loadAppsD();
        nametf.setEditable(canEdit);
        pwdtf.setEditable(canEdit);
        emailtf.setEditable(canEdit);
        hqcb.setEnabled(canEdit);
        saveb.setEnabled(canEdit);
    }
    public updateApDetails() {
        initComponents();
    } 
    void loadAppsD()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select * from user where userid='"+cuserid+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    nametf.setText(rs.getString(2));
                    emailtf.setText(rs.getString(7));
                    String Q=rs.getString(8);
                    if(Q.equals("School"))
                    {
                        hqcb.setSelectedIndex(0);
                    }
                    else if(Q.equals("PUC"))
                    {
                        hqcb.setSelectedIndex(1);
                    }
                    else if(Q.equals("BE") || Q.equals("B"))
                    {
                        hqcb.setSelectedIndex(2);
                    }
                    else if(Q.equals("M") || Q.equals("MS"))
                    {
                        hqcb.setSelectedIndex(3);
                    }
                    else if(Q.equals("PHD"))
                    {
                        hqcb.setSelectedIndex(4);
                    }
                    else
                    {
                        hqcb.setSelectedIndex(5);
                    }
                }
        }
        catch(Exception e)
        {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backb = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editstat = new javax.swing.JRadioButton();
        ln = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        lp = new javax.swing.JLabel();
        pwdtf = new javax.swing.JPasswordField();
        le = new javax.swing.JLabel();
        emailtf = new javax.swing.JTextField();
        hq = new javax.swing.JLabel();
        hqcb = new javax.swing.JComboBox<>();
        saveb = new javax.swing.JLabel();
        backgrnd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setUndecorated(true);
        setSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        backb.setBackground(new java.awt.Color(0, 102, 255));
        backb.setForeground(new java.awt.Color(255, 255, 255));
        backb.setText("     < BACK");
        backb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backb.setOpaque(true);
        backb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 417, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backb, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Make changes to your information");

        editstat.setText("    Edit");
        editstat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editstatMouseClicked(evt);
            }
        });
        editstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editstatActionPerformed(evt);
            }
        });

        ln.setText("Name");

        lp.setText("New Password");

        le.setText("email");

        hq.setText("highest qualification");

        hqcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School", "PUC", "B", "M", "PHD", "Unknown" }));

        saveb.setBackground(new java.awt.Color(0, 102, 255));
        saveb.setForeground(new java.awt.Color(255, 255, 255));
        saveb.setText("     SAVE CHANGES");
        saveb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveb.setOpaque(true);
        saveb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savebMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editstat, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(le, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ln, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nametf)
                            .addComponent(pwdtf)
                            .addComponent(emailtf)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(hq)
                                .addGap(18, 18, 18)
                                .addComponent(hqcb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saveb, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editstat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ln)
                    .addComponent(nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pwdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lp, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(le)
                    .addComponent(emailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hq)
                    .addComponent(hqcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 410, 240));

        backgrnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrmanagement/applyback.jpg"))); // NOI18N
        getContentPane().add(backgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 500, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editstatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editstatActionPerformed

    private void backbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbMouseClicked
        // TODO add your handling code here:
        appmenu ap=new appmenu();
        ap.OnStart(cuserid, cusername);
        ap.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backbMouseClicked

    private void editstatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editstatMouseClicked
        // TODO add your handling code here:
        canEdit=!canEdit;
        nametf.setEditable(canEdit);
        pwdtf.setEditable(canEdit);
        emailtf.setEditable(canEdit);
        hqcb.setEnabled(canEdit);
        saveb.setEnabled(canEdit);
    }//GEN-LAST:event_editstatMouseClicked
    private boolean isNotEMP(String str){
        
        if(str==null||str.equals("")){
            return false;
        }else{
            return true;
        }
    }
    
    private String getOldPassword()
    {
        String op="";
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="select password from user where userid='"+cuserid+"'";
                ResultSet rs=stmt.executeQuery(sql);
                if(rs.next())
                {
                    op=rs.getString(1);
                }
                
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
        return op;
    }
    
    private void savebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savebMouseClicked
        // TODO add your handling code here:
        String newName=nametf.getText().toString();
        String newPassword=pwdtf.getText().toString();
        String newEmail=emailtf.getText().toString();
        String newQ=hqcb.getSelectedItem().toString();
        
        if(!isNotEMP(newPassword))
        {
            newPassword=getOldPassword();
        }
        try{
            Class.forName("com.mysql.jdbc.Driver");  
		Connection con=DriverManager.getConnection(  
		"jdbc:mysql://localhost:3306/hrmgmt","root",""); 
                
                Statement stmt=con.createStatement();
                String sql="update user set username='"+newName+"',password='"+newPassword+"',email='"+newEmail+"',qualifications='"+newQ+"' where userid='"+cuserid+"'";
                stmt.executeUpdate(sql);
                JOptionPane.showMessageDialog(null,"Updated details ");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error "+e);
        }
        
        
    }//GEN-LAST:event_savebMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateApDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateApDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateApDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateApDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateApDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backb;
    private javax.swing.JLabel backgrnd;
    private javax.swing.JRadioButton editstat;
    private javax.swing.JTextField emailtf;
    private javax.swing.JLabel hq;
    private javax.swing.JComboBox<String> hqcb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel le;
    private javax.swing.JLabel ln;
    private javax.swing.JLabel lp;
    private javax.swing.JTextField nametf;
    private javax.swing.JPasswordField pwdtf;
    private javax.swing.JLabel saveb;
    // End of variables declaration//GEN-END:variables
}
